;;;; usb.import.scm - GENERATED BY CHICKEN 4.8.0.1 -*- Scheme -*-

(eval '(import scheme chicken foreign ports))
(##sys#register-compiled-module
  'usb
  (list)
  '((usb-find-devices . usb#usb-find-devices))
  (list)
  (list))

;; END OF FILE
